### ISSUE TITLE
Quarkus version of the project is old

### ISSUE THREAD

**Issue by Akaame** [benkard/quarkus-googlecloud-jsonlogging#1]
This project depends on a fairly old version of Quarkus: `1.13.3.Final`

Do we have the possibility of upgrading or introducing Gradle-like version ranges (if it is possible on Maven and that information is propagated to a different build system like Gradle)?

**Comment by benkard** [comment]
According to the [Maven POM reference](https://maven.apache.org/pom.html#dependency-version-requirement-specification) the dependency version, as specified, is a “soft requirement” of `1.13.3.Final` that is overridden by any earlier entry in the dependency tree, so assuming that consumers of the library specify the Quarkus version in the usual way -- as pretty much the first item in the dependency graph -- the version we specify should not have much of an effect.

That said, I would be fine with either 

1. moving to Gradle and publishing Gradle-specific “rich” version information alongside the POM, or 
2. specifying `RELEASE` as the Quarkus version in the consumer POM.

I haven't observed any other libraries using the `RELEASE` pseudo-version in transitive dependencies, so my guess is that it is probably not a good idea.

Any other ideas?

**Comment by benkard** [comment]
Updated to `2.6.1.Final` in v4.0.1.
